Repository jenkins-infra/docker-404, pull requests merged in 2025-04, with the labels that each got.

#42 chore(Jenkinsfile_updatecli): Separates updatecli pipeline
  Jenkinsfile_k8s
  Jenkinsfile_updatecli
Labels: chore

#35 chore: change updatecli author values
  updatecli/values.yaml
Labels: chore, updatecli

#43 chore(GHA) use `ubuntu-latest` runner for Release Drafter
  .github/workflows/release-drafter.yml
Labels: skip-changelog, skip-ci

#45 chore(Jenkinsfile_k8s): Remove automaticSemanticVersioning from script call
  Jenkinsfile_k8s
Labels: chore
